# Base image
FROM node:22-alpine
# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Copy the source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose port
EXPOSE 5000

# Run compiled JS
CMD ["npm", "run", "start"]
