version: "3.3"
services:
  node-app:
    container_name: express-node-app-container
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
