version: "3.3"
services:
  node-app:
    container_name: express-node-app-container  
    ports:
      - "4000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  redis:
    image: redis
volumes:
  mongo-db: